[package]
name = "uddf-sdk-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.36.1", features = ["serde", "serialize"] }
serde = { version = "1.0.210", features = ["derive"] }
