name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: target

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: target
      - name: Run tests
        run: cargo test --verbose

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy
  #       run: cargo publish --token ${CRATES_TOKEN}
  #       env:
  #         CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
